---
- name: Dynamically create host records using name server groups
  hosts: localhost
  connection: local
 
  roles:
    - { role: dynamicInfoblox }
    - { role: updateService, gridmaster_fqdn: gm.ansible.local, state: started }
