---
- name: "Update the forward zone to reflect its new Grid primary"
  nios_zone:
    name: "{{ ansible_zone }}"
    comment: forward DNS zone
    state: present
    provider: "{{ nios_provider }}"
    grid_primary:
      - name: "{{ gridmaster_fqdn }}"

#Uri module idempotecy preferred
#- name: 'Create a reverse DNS zone'
#  include_tasks: dynamic_provider_template.yml
#  vars:
#    shell_template: 'create-authoritative-reverse-zone'

- name: "Create an equivalent reverse DNS zone"
  uri:
    url: https://{{ nios_provider.host }}/wapi/{{ wapi_version }}/zone_auth
    method: POST
    user: "{{ nios_provider.username }}"
    password: "{{ nios_provider.password }}"
    body: "{{ reverse_zone_yml|to_json }}"
    #201 signifies successful creation
    #400 signifies existing entry
    #both should signify a successful WAPI call
    status_code: 201,400
    headers:
      Content-Type: "application/json"
    validate_certs: no
  register: reverse_dns_create
  changed_when: reverse_dns_create.status == 201
  vars:
    reverse_zone_yml:
      fqdn: "{{ ansible_subnet }}"
      zone_format: "IPV4"
      grid_primary:
        - name: "{{ gridmaster_fqdn }}"
...
