---
#Set this fact separately to then use in the lookup plugin
- name: Set the stored_host_count path
  set_fact:
    stored_host_count: "{{ role_path }}/files/host_record_count.txt"

- name: Keep a running count of total hostcount that have been provisioned so far using a file
  set_fact:
    ansible_host_count: "{{ lookup('file', stored_host_count) }}"

- name: 'Use the nios_next_ip lookup to get the next available IP address(es) for a given subnet'
  set_fact: 
    next_ip: "{{ lookup('nios_next_ip', ansible_subnet, provider=nios_provider) }}"
  no_log: true

- name: Create a host record at the dynamically gathered address
  nios_host_record:
    name: 'host{{ ansible_host_count }}.{{ ansible_zone }}'
    ipv4:
      - address: '{{ item }}'
    state: present
    provider: '{{ nios_provider }}'
  with_items:
    - '{{ next_ip }}'

- name: "Increment the ansible_host_count varible looked up from '{{ role_path }}/files/host_record_count.txt"
  copy:
    content: '{{ ansible_host_count|int + 1 }}'
    dest: '{{ role_path }}/files/host_record_count.txt"
...
