---
#Using a lookup like this allows for you to cumulatively stack hostnames in different subnets without having hostnames ovewrite each other between runs
- name: "Keep a running count of total hosts that have been provisioned so far"
  set_fact:
    ansible_host_count: "{{ lookup('file', stored_host_count) }}"

- name: "Use the nios_next_ip lookup to get the next available IP address(es) for a given subnet"
  set_fact: 
    next_ip: "{{ lookup('nios_next_ip', ansible_subnet, provider=nios_provider) }}"

- name: "Create a host record at the dynamically gathered address"
  nios_host_record:
    name: "host{{ ansible_host_count }}.{{ ansible_zone }}"
    ipv4:
      - address: "{{ item }}"
    state: present
    provider: "{{ nios_provider }}"
  with_items:
    - "{{ next_ip }}"

- name: "Increment the local ansible_host_count varible looked up from {{ stored_host_count }}"
  copy:
    content: "{{ ansible_host_count|int + 1 }}"
    dest: "{{ stored_host_count }}"
...
