---
- name: 'Create a dnsview named ansible'
  nios_dns_view:
    name: ansible
    state: present
    provider: '{{ nios_provider }}'

- name: 'Create some host records at hardcoded addresess and ips'
  nios_host_record:
    name: '{{ item.name }}.acme.com'
    ipv4: 
      - address: '{{ item.address }}'
    state: present
    provider: '{{ nios_provider }}'
  with_items:
    - name: servera
      address: 192.168.0.15
    - name: serverb 
      address: 192.168.0.16
    - name: serverc
      address: 192.168.0.17

#The network, host ip/address, admin, and password will need to be adjusted for the infoblox installation
#Default IP address is 192.168.1.2
- name: 'Use the nios_next_ip lookup to get the next available IP address(es) for a given subnet'
  set_fact: 
    ipaddr: "{{ lookup('nios_next_ip', '192.168.0.0/23', provider={'host': '192.168.1.2', 'username': 'admin', 'password': 'integrate'}) }}"

- name: Create a host record at the dynamically gathered address
  nios_host_record:
    name: 'dynamic.acme.com'
    ipv4:
      - address: '{{ item }}'
    state: present
    provider: '{{ nios_provider }}'
  with_items:
    - '{{ ipaddr }}'
...
