---
- name: Create dynamic records with infoblox
  include_tasks: create_records.yml
  when: snapshot_comment is undefined

- name: Take the snapshot
  include_tasks: snapshot.yml
  when: snapshot_comment is defined
