---
#Customers typically use the default view
#- name: 'Create a dnsview named ansible'
#  nios_dns_view:
#    name: ansible
#    state: present
#    provider: '{{ nios_provider }}'

- name: 'Create a test network subnet'
  nios_network: 
    network: '{{ ansible_subnet }}'
    comment: Test network subnet to add host records to
    state: present
    provider: '{{ nios_provider }}'

- name: 'Create a forward DNS local zone called ansible.local'
  nios_zone:
    name: '{{ ansible_zone }}'
    comment: DNS zone called {{ ansible_zone }}
    state: present
    provider: '{{ nios_provider }}'

- name: 'Create a reverse DNS zone called 1.168.192.in-appr.arpa'
  include_tasks: dynamic_provider_template.yml

#Having issues with the return codes - needs further investigation
#- name: 'Create a reverse DNS zone called 1.168.192.in-addr.arpa'
#  uri:
#    url: https://{{ nios_provider.host }}/wapi/v2.6/zone_auth
#    method: POST
#    user: '{{ nios_provider.username }}'
#    password: '{{ nios_provider.password }}'
#    body: "{{ reverse_zone_yml|to_json }}"
#    force_basic_auth: true
#    headers:
#      Content-Type: "application/json"
#    validate_certs: no
#  register: reverse_dns_create
#  failed_when: reverse_dns_create.status != 201 or reverse_dns_create.status != 200
#  vars:
#    reverse_zone_yml:
#      fqdn: "192.168.1.0/24"
#      zone_format: "IPV4"

- name: Create a host record for the gateway address
  nios_host_record:
    name: 'gateway.{{ ansible_zone }}'
    ipv4:
      - address: '{{ gateway_address }}'
    state: present
    provider: '{{ nios_provider }}'

- name: 'Dynamically generate {{ host_count }} host records at next available ipin {{ ansible_subnet }}'
  include_tasks: host_record_generation.yml
  loop_control:
    loop_var: count 
  with_sequence: start=1 end={{ host_count }}
...
