---
- name: "Create a name server group called {{ name_server_group }}"
  uri:
    url: "https://{{ nios_provider.host }}/wapi/{{ wapi_version }}/nsgroup"
    method: POST
    user: "{{ nios_provider.username }}"
    password: "{{ nios_provider.password }}"
    body: "{{ nsgroup_yml|to_json }}"
    #201 signifies successful creation
    #400 signifies existing entry
    #both should signify a successful WAPI call
    status_code: 201,400
    headers:
      Content-Type: "application/json"
    validate_certs: no
  register: ns_group_create
  changed_when: ns_group_create.status == 201
  vars:
    nsgroup_yml:
      name: "{{ name_server_group }}"
      grid_primary:
        - name: "{{ gridmaster_fqdn }}"

#Temporarily remove created forward zone to recreate it with ns_group
#This can likely be removed if below task converted to a PUT
- name: "Remove the forward DNS zone called {{ ansible_zone }}"
  nios_zone:
    name: "{{ ansible_zone }}"
    comment: DNS zone called {{ ansible_zone }}
    state: absent
    provider: "{{ nios_provider }}"

- name: "Update the forward zone {{ ansible_zone }} to reflect its new Grid primary as name server group {{ name_server_group }}"
  uri:
    url: "https://{{ nios_provider.host }}/wapi/{{ wapi_version }}/zone_auth"
    method: POST
    user: "{{ nios_provider.username }}"
    password: "{{ nios_provider.password }}"
    body: "{{ forward_zone_yml|to_json }}"
    #201 signifies successful creation
    #400 signifies existing entry
    #both should signify a successful WAPI call
    status_code: 201,400
    headers:
      Content-Type: "application/json"
    validate_certs: no
  register: forward_zone_create
  changed_when: forward_zone_create.status == 201
  vars:
    forward_zone_yml:
      fqdn: "{{ ansible_zone }}"
      ns_group: "{{ name_server_group }}"
      view: "default"

- name: "Create an equivalent reverse DNS zone"
  uri:
    url: "https://{{ nios_provider.host }}/wapi/{{ wapi_version }}/zone_auth"
    method: POST
    user: "{{ nios_provider.username }}"
    password: "{{ nios_provider.password }}"
    body: "{{ reverse_zone_yml|to_json }}"
    #201 signifies successful creation
    #400 signifies existing entry
    #both should signify a successful WAPI call
    status_code: 201,400
    headers:
      Content-Type: "application/json"
    validate_certs: no
  register: reverse_dns_create
  changed_when: reverse_dns_create.status == 201
  vars:
    reverse_zone_yml:
      fqdn: "{{ ansible_subnet }}"
      zone_format: "IPV4"
      ns_group: "{{ name_server_group }}"
      view: "default"
...
