---
- name: "Fail if join_grid_host is not defined"
  fail:
    msg: "Please define the grid member IP to join to the grid"
  when: join_grid_host is undefined

- name: "Join a member to the Grid" 
  uri:
    url: "https://{{ join_grid_host }}/wapi/{{ wapi_version }}/grid?_function=join"
    method: POST
    user: "{{ nios_provider.username }}" 
    password: "{{ nios_provider.password }}" 
    body: "{{ grid_join_yml|to_json }}" 
    #200 signifies successful creation
    #400 signifies existing entry
    status_code: 200, 400
    headers:
      Content-Type: "application/json"
    validate_certs: no
  register: join_to_grid
  changed_when: join_to_grid.status == 200
  vars:
    grid_join_yml:
      grid_name: "{{ grid_name }}" 
      master: "{{ nios_provider.host }}"
      shared_secret: "{{ shared_secret }}"
...
