---
#- name: Ensure that the jq package is installed
#  dnf:
#    name: jq
#    state: present

- name: Generate a snapshot of the existing records
  include_tasks: dynamic_provider_shell_template.yml
  vars:
    shell_template: 'snapshot'
    #Do not put any non alphanumeric characters or spaces for the comment
    snapshot_comment: 'AnsibleSnapshot'

- name: Remove the generated cookie file
  file:
    path: '/tmp/wapi.auth'
    state: absent
...
