---
- name: Fail the play and suggest that user needs to supply the required master_candidate values
  fail:
    msg: "Please ensure the following 4 values are supplied: master_candidate_name (fqdn only!), master_candidate_address, master_candidate_gateway, master_candidate_subnet_mask"
  when: master_candidate_name is undefined or master_candidate_address is undefined or master_candidate_gateway is undefined or master_candidate_subnet_mask is undefined

- name: Provision a gridmaster candidate
  include_tasks: dynamic_provider_shell_template.yml
  vars:
    shell_template: 'provision_gmc'

- name: Provision a gridmaster member
  include_tasks: dynamic_provider_shell_template.yml
  vars:
    shell_template: 'provision_v825'

- name: Remove the generated cookie file
  file:
    path: '/tmp/wapi.auth'
    state: absent
...
